const data = [
    {
        id: 1,
        title: "Scientists speculate that ours might not be held",
        img: "blog01.jpg",
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 2,
        title: "The Multiverse is the collection of alternate universes",
        img: "blog02.jpg",
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 3,
        title: "That share a universal hierarchy a large variety of these",
        img: "blog03.jpg",
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 4,
        title: "Universes were originated from another due to a major",
        img: "blog04.jpg",
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 5,
        title: "A hypothetical collection of potentially diverse",
        img: "blog05.jpg",
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 6,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "blog06.jpg",
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 7,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog07.jpg",
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2023",
    },
    {
        id: 8,
        title: "Observable universes each of which would comprise",
        img: "blog08.jpg",
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2023",
    }
]
export default data